services:
  app:
    entrypoint:
    - sleep
    - infinity
    dockerfile: ./Dockerfiles/Dockerfile-dev
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

